openapi: 3.0.3
info:
  title: Admin Node API
  description: Admin Node API
  version: 1.0.0
servers:
  - url: 'http://{host}/api/v1'
tags:
  - name: "node"
    description: "節點，關於主機的操作"
paths:
  /node/statuses:
    get:
      tags:
        - "node"
      summary: "get node status mapping"
      responses:
        200:
          description: ok
          content:
            application/json:
              example:
                {
                  "result": [
                    {"id": 0,"description": "ok"},
                    {"id": 1,"description": "updating"},
                    {"id": 2,"description": "not response"},
                  ]
                }
  /node/types:
    get:
      tags:
        - "node"
      summary: "get node type mapping"
      responses:
        200:
          description: ok
          content:
            application/json:
              example:
                {
                  "result": [
                    {"id": 0,"description": ""},
                    {"id": 1,"description": "layer1-node"},
                    {"id": 2,"description": "layer2-node"},
                  ]
                }